{"uuid": "4c309702-949e-4f30-acf9-40cf9ae1f7ec", "children": ["f42cae86-6b96-4adc-8885-cfc055e4b9db"], "befores": [{"name": "setupbrowser", "status": "passed", "start": 1739870269885, "stop": 1739870273377}], "afters": [{"name": "setupbrowser::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\tests\\conftest.py\", line 58, in setupbrowser\n    driver.quit()\n    ~~~~~~~~~~~^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 152, in stop\n    self.send_remote_shutdown_command()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 137, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 126, in is_connectable\n    return utils.is_connectable(self.port)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"C:\\Program Files\\Python313\\Lib\\socket.py\", line 856, in create_connection\n    exceptions.clear()  # raise only the last error\n    ~~~~~~~~~~~~~~~~^^\n"}, "start": 1739870273899, "stop": 1739870278103}], "start": 1739870269885, "stop": 1739870278103}