{"uuid": "80b9d972-712f-4b20-8595-8778371d51a8", "children": ["daf20120-58ee-4178-9d39-cc410635f3b5"], "befores": [{"name": "setupbrowser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=132.0.6834.197)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6B22802F5+28725]\n\t(No symbol) [0x00007FF6B21E2AE0]\n\t(No symbol) [0x00007FF6B207510A]\n\t(No symbol) [0x00007FF6B204EEA5]\n\t(No symbol) [0x00007FF6B20F6F87]\n\t(No symbol) [0x00007FF6B210FA52]\n\t(No symbol) [0x00007FF6B20EFD53]\n\t(No symbol) [0x00007FF6B20BA0E3]\n\t(No symbol) [0x00007FF6B20BB471]\n\tGetHandleVerifier [0x00007FF6B25AF30D+3366989]\n\tGetHandleVerifier [0x00007FF6B25C12F0+3440688]\n\tGetHandleVerifier [0x00007FF6B25B78FD+3401277]\n\tGetHandleVerifier [0x00007FF6B234AAAB+858091]\n\t(No symbol) [0x00007FF6B21EE74F]\n\t(No symbol) [0x00007FF6B21EA304]\n\t(No symbol) [0x00007FF6B21EA49D]\n\t(No symbol) [0x00007FF6B21D8B69]\n\tBaseThreadInitThunk [0x00007FF8292F7374+20]\n\tRtlUserThreadStart [0x00007FF82A31CC91+33]\n\n", "trace": "  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\tests\\conftest.py\", line 54, in setupbrowser\n    driver.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739792621436, "stop": 1739792627078}], "start": 1739792621436, "stop": 1739792627426}