{"uuid": "9fa867ed-1954-46d4-a06f-9fa6e9794603", "children": ["4363d380-71df-42c3-a5b3-fa4036bfb216"], "befores": [{"name": "setupbrowser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=132.0.6834.197)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6F46702F5+28725]\n\t(No symbol) [0x00007FF6F45D2AE0]\n\t(No symbol) [0x00007FF6F446510A]\n\t(No symbol) [0x00007FF6F443EEA5]\n\t(No symbol) [0x00007FF6F44E6F87]\n\t(No symbol) [0x00007FF6F44FFA52]\n\t(No symbol) [0x00007FF6F44DFD53]\n\t(No symbol) [0x00007FF6F44AA0E3]\n\t(No symbol) [0x00007FF6F44AB471]\n\tGetHandleVerifier [0x00007FF6F499F30D+3366989]\n\tGetHandleVerifier [0x00007FF6F49B12F0+3440688]\n\tGetHandleVerifier [0x00007FF6F49A78FD+3401277]\n\tGetHandleVerifier [0x00007FF6F473AAAB+858091]\n\t(No symbol) [0x00007FF6F45DE74F]\n\t(No symbol) [0x00007FF6F45DA304]\n\t(No symbol) [0x00007FF6F45DA49D]\n\t(No symbol) [0x00007FF6F45C8B69]\n\tBaseThreadInitThunk [0x00007FFC1BFC7374+20]\n\tRtlUserThreadStart [0x00007FFC1CD5CC91+33]\n\n", "trace": "  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\tests\\conftest.py\", line 54, in setupbrowser\n    driver.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 536, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Dell\\PycharmProjectHRMS.PYTEST\\pythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739860501210, "stop": 1739860506332}], "start": 1739860501210, "stop": 1739860506708}